### ISSUE TITLE
Development installation not working

### ISSUE THREAD

**Issue by aktech** [Carreau/papyri-lab#4]
I followed the development installation instructions from the `README` and it doesn't seems to work, here is what I did:

```
conda create -n plab38 python=3.8 -c conda-forge --yes
```

Then ran the installation from the README.md

```bash
# Clone the repo to your local environment
# Change directory to the papyri_lab directory
# Install package in development mode
pip install -e .
# Link your development version of the extension with JupyterLab
jupyter labextension develop . --overwrite
# Server extension must be manually installed in develop mode
jupyter server extension enable papyri_lab
# Rebuild extension Typescript source after making changes
jlpm build
```

Output Error:

```
Jupyter command `jupyter-labextension` not found.
Enabling: papyri_lab
- Writing config: /Users/aktech/miniconda3/envs/plab38/etc/jupyter
    - Validating papyri_lab...
/Users/aktech/quansight/papyri-lab/papyri_lab/handlers.py:20: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if module is "*":
      papyri_lab 0.1.0 OK
    - Extension successfully enabled.
zsh: command not found: jlpm
```

I installed `jupyterlab` after this

```
pip install jupyterlab
```

Then I got the following error:

```
WARNING: Build tool `jupyter-packaging` is missing. Install it with pip or conda.
Installing /Users/aktech/quansight/papyri-lab/papyri_lab/labextension -> papyri-lab
Symlinking: /Users/aktech/miniconda3/envs/plab38/share/jupyter/labextensions/papyri-lab -> /Users/aktech/quansight/papyri-lab/papyri_lab/labextension
Traceback (most recent call last):
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 320, in add_extension
    extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 166, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/traitlets.py", line 1361, in __init__
    value = self._traits[key]._cross_validate(self, getattr(self, key))
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/traitlets.py", line 746, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/traitlets.py", line 1233, in __call__
    return self.func(*args, **kwargs)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 175, in _validate_name
    self._module, self._metadata = get_metadata(name)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/utils.py", line 60, in get_metadata
    module = importlib.import_module(package_name)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server_terminals/__init__.py", line 9, in <module>
    raise RuntimeError("Jupyter Server Terminals requires Jupyter Server 2.0+")
RuntimeError: Jupyter Server Terminals requires Jupyter Server 2.0+


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aktech/miniconda3/envs/plab38/bin/jupyter-server", line 8, in <module>
    sys.exit(main())
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_core/application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/config/application.py", line 1043, in launch_instance
    app.start()
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2774, in start
    self.start_app()
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2670, in start_app
    super().start()
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_core/application.py", line 274, in start
    self.subapp.start()
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/serverextension.py", line 378, in start
    super().start()
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_core/application.py", line 274, in start
    self.subapp.start()
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/serverextension.py", line 272, in start
    self.toggle_server_extension(arg)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/serverextension.py", line 241, in toggle_server_extension
    config_dir, extension_manager = _get_extmanager_for_context(
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/serverextension.py", line 60, in _get_extmanager_for_context
    extension_manager = ExtensionManager(
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/config/configurable.py", line 85, in __init__
    super().__init__(**kwargs)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/traitlets.py", line 1368, in __init__
    self.notify_change(changes[key])
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/traitlets.py", line 1517, in notify_change
    return self._notify_observers(change)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/traitlets/traitlets.py", line 1564, in _notify_observers
    c(event)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 253, in _config_manager_changed
    self._load_config_manager(change.new)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 308, in _load_config_manager
    self.from_jpserver_extensions(jpserver_extensions)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 313, in from_jpserver_extensions
    self.add_extension(name, enabled=enabled)
  File "/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyter_server/extension/manager.py", line 325, in add_extension
    if self.serverapp.reraise_server_extension_failures:
AttributeError: 'NoneType' object has no attribute 'reraise_server_extension_failures'

Internal Error: papyri-lab@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:435:5145)
    at xf.getCandidates (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:391:1264)
    at /Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:439:7693
    at ff (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:390:11070)
    at ge (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:439:7673)
```

**Comment by Carreau** [comment]
You likely want to pin to jupyterlab 2.x

**Comment by aktech** [comment]
Yeah, I installed that and managed to get it working.

Although this error didn't went away until I ran `jlpm` before `jlpm build`

```
Internal Error: papyri-lab@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at q0.getCandidates (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:435:5145)
    at xf.getCandidates (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:391:1264)
    at /Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:439:7693
    at ff (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:390:11070)
    at ge (/Users/aktech/miniconda3/envs/plab38/lib/python3.8/site-packages/jupyterlab/staging/yarn.js:439:7673)
(plab38)  ✘ aktech@aklabsm  quansight/papyri-lab   main ●(ba2b717)  jupyter server extension enable papyri_lab
```

**Comment by aktech** [comment]
Is there a document/instructions on how to use the extension?

Doing `??` doesn't seems to work:

<img width="702" alt="Screenshot 2023-06-15 at 3 36 21 pm" src="https://github.com/Carreau/papyri-lab/assets/5647941/16f0bc7e-09a4-4508-b6de-7e4bff608c2e">

**Comment by Carreau** [comment]
I've always been confused about exactly how to use jlpm, but I can try rebuilding it. On the IPython side you will need [this branch](https://github.com/Carreau/ipython/tree/papyri-hook-example), and you may need an old version of Papyri, unsure.

**Comment by Carreau** [comment]
I had some uncommited local upadte, likely from Scipy, I also updated a bit thre readme with explanations.

**Comment by aktech** [comment]
Awesome, thanks! Let me take a look.

**Comment by Carreau** [comment]
I'll see if I can get it to work again in the next few days. Right now I'm going to try to respond to rowan and steve to get a snippet to render with react

**Comment by aktech** [comment]
This is fixed.
